<?php

/**
 * @file
 * Contains views_extras.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_extras module.
    case 'help.page.views_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom extra&#039;s for Views. authored by norwegian.blue') . '</p>';
      return $output;

    default:
  }
}
